services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
      POSTGRES_DB: intent_app
  cache:
    image: redis
    ports:
      - '6379:6379'
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      - MAILDEV_INCOMING_USER=admin@blogify.com
      - MAILDEV_INCOMING_PASS=admin@123
